### PR TITLE
Create new, dedicated plug-in to generate Java code from XSD

### PR DESCRIPTION
**Pull request by ptziegler**
The Java code is generated automatically via the jaxb2-maven-plugin and therefore not checked in. With the latest m2e version, this Mojo should be executed as part of the incremental build.
By using those POJOs, we are able to process the XML extension contribution instead of Digester3.

Note that processing the generated code is done via the JAXB API. Meaning that this approach adds a dependency to jakarta.xml.bind (and jakarta.activation). While the project depends on the latest version, we are compatible with all versions starting from 3.0.0.

#638

### CODE REVIEW

**Comment by ptziegler** [comment]
The way I understand digester3 is that you can bind "rules" to a given XPath. Whenever this path is detected inside an XML, the rule is then executed with the attribute at that given location.

My idea is to generate Java POJOs from our schema and then initialize those objects using FasterXML. We can then simply access the attributes via getters.

**Comment by merks** [comment]
Will the setup generate what’s not checked in?

**Comment by ptziegler** [comment]
> Will the setup generate what’s not checked in?

Yes, the version of m2e that's installed with the setup is already smart enough to automatically detect and execute the jaxb2 goal :)

**Comment by ptziegler** [comment]
That being said, Maven seems to be unable to understand the "file:${project_loc:/target-platform}/mvn/wb-mvn.target" URI in the target-platform definition... So it's still not perfect.

**Comment by merks** [comment]
I wish relative paths worked.

**Comment by ptziegler** [comment]
I'll split this migration up into several parts, with this one covering the creation of the XSD plugin and the removal of Digester3 for the LayoutDescription class.

Otherwise this'd be a very big PR.

As mentioned earlier, the classes are generated as part of the incremental build. Meaning that as long as m2e is installed via Oomph, the workspace should still compile out-of-the-box.

**Pull request merged**
