### PR TITLE
ComponentDescriptor should use ImageDescriptors instead of Images

### PR DESCRIPTION
**Pull request by ptziegler**
This also removes a lot of the unnecessary conversion from Images to ImageDescriptors via the ImageImageDescriptor wrapper.

### CODE REVIEW

**Comment by ptziegler** [comment]
#260 #486

**Comment by merks** [comment]
@ptziegler 

It's great to see so much active improvement!  

FYI, this is M2 week, so you may wish to do a milestone build and contribute it.  Please reach out to me for **anything** I can do to help!

**Comment by ptziegler** [comment]
> FYI, this is M2 week, so you may wish to do a milestone build and contribute it. Please reach out to me for anything I can do to help!

Thanks for the reminder :) Luckily, all that's left is cleaning up the remaining image wrappers. Ideally I can get main part finished by tomorrow, so that we can build the M2 on Tuesday or Wednesday.
It'd be awesome if you have some time available, to contribute it to the SimRel releases train.

**Comment by merks** [comment]
Ping we when there is a milestone repository and I'll make sure it's contributed.  😁

**Pull request merged**
