### PR TITLE
Update XWT to 1.9.0 in replacement for the embedded jars.

### PR DESCRIPTION
**Pull request by ptziegler**
The embedded XWT jars have been introduced with the initial contribution and not been updated since then. These bundles are no longer compatible with recent Eclipse releases, due to references to deprecated classes, which have since been removed.
Updating to the latest release and adapting the package names seem to have been sufficient to restore the XWT editor.

Reverts c65201c28d293ac1474f8a144b1ea41b48e56aef

### CODE REVIEW

**Comment by ptziegler** [comment]
Note that there doesn't seem to be a "nightly build" repository at https://download.eclipse.org/xwt/, which is why I've had to add the 2023-06 release to the Oomph script.
I've also added the XWT tests to the main suite. Given that they have never been executed up until now, there's a good chance a lot of them are broken. I'll probably disable those for the time being.

resolves #362

**Comment by merks** [comment]
FYI, the Papyrus folks disabled the XWT contribution to SimRel. 

https://git.eclipse.org/c/simrel/org.eclipse.simrel.build.git/commit/?id=247a40021c9968b4e62149a96834c6437ad44390

 I can re-enable it, if WindowBuilder will be relying on it and I assume that will be problem free.

But please also note it's this version:

https://download.eclipse.org/xwt/release-1.9.0/

**Comment by ptziegler** [comment]
> FYI, the Papyrus folks disabled the XWT contribution to SimRel.

That's a real shame :( Given that the adaptations to get XWT functional again were rather small, I'd like to keep supporting it for as long as it's feasible. Though I wouldn't want to decide over the heads of the Papyrus developers, whether XWT should be contributed or not.

But otherwise, if it's not part of the SimRel release the we'd only have to explicitly add the update site to the target platform definition. That's also what I'd prefer, personally...
Thanks for the heads up!

**Comment by ptziegler** [comment]
> I will re-enable it if WindowBuilder needs it. Just please test that it works with version 1.19.0 if at all possible.
> Okay?

Sounds like a plan. I've quickly created https://github.com/ptziegler/windowbuilder/pull/14 where I build this branch against the latest XWT release.

**Comment by ptziegler** [comment]
@merks The tests are green and the editor works without a problem

image

**Comment by ptziegler** [comment]
I also made a slight mistake with the title: Tycho is already using the 1.9.0, so even the tests here run against the latest version.

image

**Comment by merks** [comment]
Great!

**Comment by ptziegler** [comment]
The test failure is unrelated to XWT and seems to be caused by the lovely "The process cannot delete X because it's currently used by another process" error on Windows... I have to dig up my laptop to figure out a good way to deal with this :/

**Comment by merks** [comment]
> The test failure is unrelated to XWT and seems to be caused by the lovely "The process cannot delete X because it's currently used by another process" error on Windows... I have to dig up my laptop to figure out a good way to deal with this :/

I hate that problem!!

**Pull request merged**
